/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_Permissions;
import BLL.BLL_Role;
import DTO.DTO_Permissions;
import DTO.DTO_Role;
import static GUI.GUI_Customer.permissionses;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import ultils.CustomCombo;

/**
 *
 * @author Nhat
 */
public class GUI_Role extends javax.swing.JFrame {

    static BLL_Role bLL_Role = new BLL_Role();
    static BLL_Permissions bLL_Permissions = new BLL_Permissions();
    ArrayList<DTO_Role> ListRole = null;
    static ArrayList<DTO_Permissions> permissionses = null;
    /**
     * Creates new form GUI_Role
     */
    public GUI_Role(ArrayList<DTO_Permissions> permissions) throws SQLException {
        initComponents();
        permissionses = permissions;
        LoadListRole();
        LoadRoleDetailDefault();
        Setdefault();
        LoadPermissions();
    }
    public void LoadPermissions() {
        if (!permissionses.get(0).isAllowInsert()) {
            btn_AddnewRole.setEnabled(false);
        }
        if (!permissionses.get(0).isAllowDelete()) {
            btn_Delete.setEnabled(false);
        }
        if (!permissionses.get(0).isAllowUpdate()) {
            btn_Update.setEnabled(false);
        }
    }

    public void LoadListRole() throws SQLException {
        
        ListRole = bLL_Role.GetAllRole();
        DefaultComboBoxModel mod_Supplier = new DefaultComboBoxModel();
        for (int i = 0; i < ListRole.size(); i++) {
            // create object(is a row in table) 
            Object items_Role = new CustomCombo(ListRole.get(i).getId(), ListRole.get(i).getName());
            mod_Supplier.addElement(items_Role);
        }
        cmb_Role.setModel(mod_Supplier);

    }

    public void LoadRoleDetailDefault() {

        String[] columnNames = new String[]{" RoleId ", " Model ", "AllowInsert", "AllowSelect", "AllowUpdate","AllowDelete"};
        DefaultTableModel model = new DefaultTableModel(null, columnNames) {
            @Override
            public Class getColumnClass(int columnIndex) {
                if(columnIndex!=0 && columnIndex!=1){
                   return Boolean.class;
                }else{
                    return Integer.class;
                }
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // or a condition at your choice with row and column
            }
        };
        //model.addRow(new Object[]{0,0,false,false,false,false});
//        for(int i = 0 ;i<8;i++){
//            model.addRow(new Object[]{0,0,false,false,false,false});
//        }
        Table_RoleDetail.setModel(model);
        cmb_Role.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                try {
                    CustomCombo Role = (CustomCombo) cmb_Role.getSelectedItem();
                    ArrayList<DTO_Permissions> permissionses = bLL_Permissions.GetPermissionsByRoleId(Role.getID());
                    DefaultTableModel model = (DefaultTableModel) Table_RoleDetail.getModel();
                    model.setRowCount(0);
                    for(int i = 0; i<permissionses.size();i++){
                        model.addRow(new Object[]{Role.getID(),permissionses.get(i).getModelId(),
                            permissionses.get(i).isAllowInsert(),permissionses.get(i).isAllowSelect(),
                            permissionses.get(i).isAllowUpdate(),permissionses.get(i).isAllowDelete()});
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Role.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void Setdefault(){
        cmb_Role.setSelectedIndex(1);
        cmb_Role.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_RoleList = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmb_Role = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel_RoleDetail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_RoleDetail = new javax.swing.JTable();
        btn_Update = new javax.swing.JButton();
        btn_AddnewRole = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("List Role");

        cmb_Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel_RoleListLayout = new javax.swing.GroupLayout(jPanel_RoleList);
        jPanel_RoleList.setLayout(jPanel_RoleListLayout);
        jPanel_RoleListLayout.setHorizontalGroup(
            jPanel_RoleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RoleListLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RoleListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_Role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_RoleListLayout.setVerticalGroup(
            jPanel_RoleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RoleListLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(cmb_Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        jLabel1.setText("Role");

        Table_RoleDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_RoleDetail);

        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_AddnewRole.setText("Add New Role");
        btn_AddnewRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddnewRoleActionPerformed(evt);
            }
        });

        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("model : \n\t1 Role\n\t2 Employee\n\t3 Category\n\t4 Supplier\n\t5 Product\n\t6 Customer\n\t7 Customer Order\n\t8 Company Order\t");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel_RoleDetailLayout = new javax.swing.GroupLayout(jPanel_RoleDetail);
        jPanel_RoleDetail.setLayout(jPanel_RoleDetailLayout);
        jPanel_RoleDetailLayout.setHorizontalGroup(
            jPanel_RoleDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel_RoleDetailLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btn_AddnewRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_RoleDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel_RoleDetailLayout.setVerticalGroup(
            jPanel_RoleDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RoleDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_RoleDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Update)
                    .addComponent(btn_AddnewRole)
                    .addComponent(btn_Delete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_RoleList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_RoleDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(283, 283, 283))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel_RoleDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jPanel_RoleList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddnewRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddnewRoleActionPerformed
        // TODO add your handling code here:
        try {
            GUI_Insert_Update_Role jframeGUI_Insert_Update_Role = new GUI_Insert_Update_Role(null,this);
            jframeGUI_Insert_Update_Role.pack();
            jframeGUI_Insert_Update_Role.setLocationRelativeTo(null);
            jframeGUI_Insert_Update_Role.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jframeGUI_Insert_Update_Role.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_AddnewRoleActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        CustomCombo role = (CustomCombo) cmb_Role.getSelectedItem();
        try {
            GUI_Insert_Update_Role jframeGUI_Insert_Update_Role = new GUI_Insert_Update_Role(role,this);
            jframeGUI_Insert_Update_Role.pack();
            jframeGUI_Insert_Update_Role.setLocationRelativeTo(null);
            jframeGUI_Insert_Update_Role.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jframeGUI_Insert_Update_Role.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        CustomCombo role = (CustomCombo) cmb_Role.getSelectedItem();
        if(role.getID()!=1){
            try {
                bLL_Role.Delete(role.getID(),this);
                
            } catch (SQLException ex) {
                Logger.getLogger(GUI_Role.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_Role(permissionses).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Role.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_RoleDetail;
    private javax.swing.JButton btn_AddnewRole;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> cmb_Role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_RoleDetail;
    private javax.swing.JPanel jPanel_RoleList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
